apiVersion: v1
kind: Namespace
metadata:
  name: sched-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-intensive
  namespace: sched-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cpu-intensive
  template:
    metadata:
      labels:
        app: cpu-intensive
    spec:
      schedulerName: default-scheduler
      containers:
      - name: cpu-intensive
        image: nginx:alpine
        resources:
          requests:
            cpu: "2"
            memory: "256Mi"
          limits:
            cpu: "2"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-intensive
  namespace: sched-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: memory-intensive
  template:
    metadata:
      labels:
        app: memory-intensive
    spec:
      schedulerName: default-scheduler
      containers:
      - name: memory-intensive
        image: nginx:alpine
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: "0.5"
            memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: balanced
  namespace: sched-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: balanced
  template:
    metadata:
      labels:
        app: balanced
    spec:
      schedulerName: default-scheduler
      containers:
      - name: balanced
        image: nginx:alpine
        resources:
          requests:
            cpu: "1"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "512Mi" 