apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: custom-multiresource-scheduler
      plugins:
        filter:
          enabled:
          - name: MultiResource
        score:
          enabled:
          - name: MultiResource
            weight: 5
      pluginConfig:
      - name: MultiResource
        args:
          alpha: 0.5
          maxScore: 100
          prometheusURL: "http://prometheus-server.default.svc.cluster.local:80" 