apiVersion: v1
kind: Pod
metadata:
  name: test-multiresource-pod
  labels:
    test: multiresource
spec:
  schedulerName: custom-multiresource-scheduler
  containers:
  - name: nginx
    image: nginx:1.19
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "200m"
        memory: "200Mi" 