apiVersion: v1
kind: Pod
metadata:
  name: custom-multiresource-test-pod-minimal
  annotations:
    scheduler.extender/disk-read: "10M"  # 10 MB/s read
    scheduler.extender/disk-write: "5M" # 5 MB/s write
    scheduler.extender/net-up: "2M"      # 2 MB/s upload
    scheduler.extender/net-down: "5M"   # 5 MB/s download
spec:
  schedulerName: custom-multiresource-scheduler
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx:1.19
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"
  terminationGracePeriodSeconds: 0 