apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-extender
  namespace: kube-system
  labels:
    component: scheduler-extender
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduler-extender
  template:
    metadata:
      labels:
        component: scheduler-extender
    spec:
      serviceAccountName: scheduler-extender-sa
      containers:
      - name: scheduler
        image: cyrusho777/scheduler-extender:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
          name: http
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus-server.default.svc.cluster.local:80/api/v1/query"
        - name: MULTIRESOURCE_ALPHA
          value: "0.8"
        - name: MULTIRESOURCE_MAXSCORE
          value: "100"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 20
