apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-extender-policy
  namespace: kube-system
data:
  policy.cfg: |
    {
      "kind": "Policy",
      "apiVersion": "v1",
      "extenders": [
        {
          "urlPrefix": "http://scheduler-extender.kube-system.svc.cluster.local:8888",
          "filterVerb": "filter",
          "prioritizeVerb": "prioritize",
          "weight": 1,
          "enableHTTPS": false,
          "nodeCacheCapable": false,
          "httpTimeout": 30000000000,
          "managedResources": [
            {
              "name": "scheduler.extender/cpu-memory",
              "ignoredByScheduler": false
            }
          ]
        }
      ]
    } 