apiVersion: v1
kind: Service
metadata:
  name: scheduler-extender
  namespace: kube-system
  labels:
    component: scheduler-extender
spec:
  selector:
    component: scheduler-extender
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  type: ClusterIP 