apiVersion: v1
kind: Pod
metadata:
  name: scheduler-extender-test-pod
  labels:
    app: scheduler-test
  annotations:
    scheduler-test: "true"
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
    - containerPort: 80
  # Add tolerations to allow scheduling on master nodes
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  # Don't restart if the pod fails or completes
  restartPolicy: Never 